### ISSUE TITLE
Block comments

### ISSUE THREAD

**Issue by bbrk24** [zackradisic/aussieplusplus#14]
The syntax highlighting suggests `/* ... */` comments exist, but using one causes an error.

**Comment by zackradisic** [comment]
Yeah I didn't get around to implementing block comments, should be a trivial thing to add. Before I do, anyone have any ideas for making them more strayan? Here's an idea:

```go
OI MATE!
Everything inside of here is commented out
GOT IT?!
```

**Comment by jwfxpr** [comment]
Oh that's great, but some flexibility in syntax would be good. It should be equally valid to start a comment block with other vocative forms. In other words, `OI DRONGO!` or `OI D***HEAD!` should also work, no?

**Comment by bbrk24** [comment]
The main reason I suggested it was so I could do comments inline, like `f(/* comment here */);`. That being said, I like your idea too much to say no. It also lines up with now everything before the `G'DAY MATE!` is ignored.

**Comment by zackradisic** [comment]
Added support for block comments:

```go
OI MATE!
This is a comment
GOT IT?
```

**Comment by bbrk24** [comment]
@zackradisic I don't see them in the documentation anywhere.
