### ISSUE TITLE
Extra output: `EXpr is: ExprNode ...`

### ISSUE THREAD

**Issue by bbrk24** [zackradisic/aussieplusplus#27]
This short program, which should print nothing:

```
G'DAY MATE!

I RECKON i IS A WALKABOUT FROM [1 TO 7] <
>

CHEERS C***!
```

Instead prints:

> ```
> EXpr is: ExprNode { expr: Literal(Number(7.0)), line: 3 }
> ```

**Comment by zackradisic** [comment]
Fixed, thx!
