### ISSUE TITLE
thread 'main' panicked at 'Unable to resolve var'

### ISSUE THREAD

**Issue by bbrk24** [zackradisic/aussieplusplus#28]
Perhaps a mistyped variable name should give a more readable error message than this?

> ```
> thread 'main' panicked at 'Unable to resolve var: Var { ident: Ident { name: "h", line: 11 }, scope_distance: 4294967295 }', src/resolver.rs:211:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Hitting "Run" a second time without fixing the issue also yields the `thread panicked while panicking.` error mentioned in #16.

**Comment by zackradisic** [comment]
Fixed!
