### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by bbrk24** [zackradisic/aussieplusplus#30]
There doesn't seem to be any documentation on block comments or increment/decrement statements, even though the issues for them were closed.

**Comment by jwfxpr** [comment]
Partially addressed this is #32, which documents comments including block comments.

Will also add increment and decrement to docs today or tomorrow!

**Comment by jwfxpr** [comment]
@bbrk24 #32 now documents comments as well as inc/dec expressions 👍

**Comment by zackradisic** [comment]
Fixed by #32
