### ISSUE TITLE
Fix quotes in upside-down mode

### ISSUE THREAD

**Issue by bbrk24** [zackradisic/aussieplusplus#31]
Right now, both `„` and `"` are valid in upside-down mode, while only the latter are valid in rightside-up mode.

Relatedly, [`examples/upsidedown.aussie`](https://github.com/zackradisic/aussieplusplus/blob/master/examples/upsidedown.aussie) needs to be changed.

**Comment by jwfxpr** [comment]
@bbrk24 PR #34 fixes the example, good catch

**Comment by zackradisic** [comment]
Fixed by #34
