### ISSUE TITLE
Increment/decrement statements

### ISSUE THREAD

**Issue by jwfxpr** [zackradisic/aussieplusplus#7]
`GOOD ON YA` as increment statement:

```
I RECKON x = 0;
GOOD ON YA x;
GIMME x;
// Output is 1
```

`PULL YA HEAD IN` as decrement statement:

```
I RECKON x = 1;
PULL YA HEAD IN x;
GIMME x;
// Output is 0
```

I would expect these to be pre-inc/decrements, where that's relevant

**Comment by jwfxpr** [comment]
Wanting to dig into this codebase has motivated me to (finally) start properly learning Rust, and doing so has led me to think that we should _not_ include post-dec/increment in aussie++, for much the same reasons that inc/dec unaries are excluded from Rust (ref for curious readers: [Rust FAQ](https://github.com/dtolnay/rust-faq#why-doesnt-rust-have-increment-and-decrement-operators)).

Still really wanna see `GOOD ON YA x` and `PULL YA HEAD IN x` as unambiguous increment/decrement expressions equivalent to `x += 1` and `x -= 1` though 😁

**Comment by zackradisic** [comment]
@jwfxpr really excited about you learning Rust, it's a great language and I could definitely use some help! I should write an ARCHITECTURE.md or something of the sort to help ppl navigate the code 👍

As for the incr/decr expressions, keeping them in the prefix position sounds good to me.

**Comment by jwfxpr** [comment]
Yeah mate, drifting off topic here but... is there such a thing as a Rustgasm? Rust is what I didn't realise I needed in my life. It's like I didn't realise I had a headache my whole life until it just started going away.

I would definitely encourage at least a CONTRIBUTING.md, and considering the rate at which the repository is accumulating stars and forks, I think you can anticipate more contributions incoming. We can open a contributing issue if you want input on that stuff, but one thing that I think would be nice to see is the [All Contributors spec](https://github.com/all-contributors/all-contributors), since you _already_ have really valuable contributions that aren't coming from PRs. 😊

Now, one last back-on-topic note: Implementing this would mean that this language could correctly be referred to as `GOOD ON YA AUSSIE`, which... I mean... is obviously amazing 😂

**Comment by zackradisic** [comment]
Yeah I definitely felt the same way about Rust, I started an issue for contributing #21 and just added the All Contributors bot 👍
